title: Bozhen Liu
logo: /assets/img/Bozhen-Liu-Photo.jpg
description: Assistant Professor 
department: Department of Computer Science
university: Texas A&M University - Corpus Christi
email: Email:bozhen.liu@tamucc.edu
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github:
  prev_url: https://github.com/april1989

author:
  googlescholar: https://scholar.google.com/citations?user=tfq2RlMAAAAJ&hl=en
  lab: https://bozhen-liu.github.io/
